CREATE TABLE URAT_BLOB
(
  ID       NUMBER(10)                           NOT NULL,
  CONTENT  BLOB
);

ALTER TABLE URAT_BLOB ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

CREATE TABLE URAT_UPLOADS
(
  ID         NUMBER(10)                         NOT NULL,
  EXT        VARCHAR2(4 CHAR),
  NAME       VARCHAR2(200 CHAR),
  PATH       VARCHAR2(250 CHAR),
  FILE_SIZE  VARCHAR2(50 CHAR),
  BLOB_ID    NUMBER(10)
);

ALTER TABLE URAT_UPLOADS ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE URAT_UPLOADS ADD (
  CONSTRAINT  
  FOREIGN KEY (BLOB_ID) 
  REFERENCES URAT_BLOB (ID)
  ENABLE VALIDATE);
  
CREATE TABLE URAT_DOCUMENTS
(
  ID           NUMBER(10)                       NOT NULL,
  CATEGORY     VARCHAR2(100 CHAR),
  CREATED      TIMESTAMP(6),
  DESCRIPTION  VARCHAR2(2000 CHAR),
  MODIFIED     TIMESTAMP(6),
  NAME         VARCHAR2(100 CHAR),
  STAGE        VARCHAR2(100 CHAR),
  STATE        NUMBER(1)                        NOT NULL,
  TYPE         NUMBER(10),
  FILE_ID      NUMBER(10)
);

ALTER TABLE URAT_DOCUMENTS ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE URAT_DOCUMENTS ADD (
  CONSTRAINT 
  FOREIGN KEY (FILE_ID) 
  REFERENCES URAT_UPLOADS (ID)
  ENABLE VALIDATE);
 
CREATE TABLE URAT_RULE_FILES
(
  ID        NUMBER(10)                          NOT NULL,
  CREATED   TIMESTAMP(6),
  MODIFIED  TIMESTAMP(6),
  NAME      VARCHAR2(100 CHAR),
  STATE     NUMBER(1)                           NOT NULL,
  FILE_ID   NUMBER(10)
);

ALTER TABLE URAT_RULE_FILES ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE URAT_RULE_FILES ADD (
  CONSTRAINT  
  FOREIGN KEY (FILE_ID) 
  REFERENCES URAT_UPLOADS (ID)
  ENABLE VALIDATE);
  
CREATE TABLE URAT_USERS
(
  ID        NUMBER(10)                          NOT NULL,
  CREATED   TIMESTAMP(6),
  ENABLED   NUMBER(1)                           NOT NULL,
  PASSWORD  VARCHAR2(40 CHAR),
  USERNAME  VARCHAR2(50 CHAR)
);

ALTER TABLE URAT_USERS ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  UNIQUE (USERNAME)
  ENABLE VALIDATE);
